var IMAGES = [
	["1.jpg",					"Ahhh a Dementor!!!"],
	["victory dance.jpg",		"Opa Harbaugh Style!"],
	["3.jpg", 					"Ohhhh Snap!"],
	["4.jpg",					"oh no he di'iint!!!!!"],
	["5.jpg",					"I feel like I'm taking crazy pills!!!"],
	["2.jpg",					"Use the Force, Padawan"],
	["happy and you.jpg",		"If you're happy and you know it, clap your hands!"],
	["beats by harbaugh.jpg",	"Beats By Harbaugh"],
	["penalty.jpg",				"Penalty"],
	["first down.jpg",			"Cheeeeck out my HarbaughStrong band!"],
	["oops i did it again.jpg",	"Oops!..  I did it again. I played with your heart..."],
	["files are in the headphones.jpg", "The files are IN the headphones??"],
	["spirit fingers.jpg",		"Spirit Fingers!"],
	["offsides.jpg",			"Offsides"],
	["interception.gif",		"They inceptioned us!!?"],
	["4th and 1.jpg",			"4th and 1"],
	["touchdown.jpg",			"I love you this much"],
	["field goal.jpg",			"Wowwwww thats a big TV screen!"],
	["win game.jpg",			"Win Game"],
	["holding.gif",				"Holding"],
	["halftime.jpg",			"Halftime"],
];