var IMAGES = [
	["1.jpg",					"Ahhh a Dementor!!!"],
	["victory dance.jpg",		"Opa Harbaugh Style!"],
	["3.jpg", 					"Ohhhh Snap!"],
	["4.jpg",					"oh no he di'iint!!!!!"],
	["5.jpg",					"I feel like I'm taking crazy pills!!!"],
	["2.jpg",					"Use the Force, Padawan"],
	["happy and you.jpg",		"If you're happy and you know it, clap your hands!"],
	["beats by harbaugh.jpg",	"Beats By Harbaugh"],
	["mr congeniality.jpg",		"Mr. Congeniality"],
	["spoon.jpg", 				"I knew I wanted to be a football coach the first time I caught my reflection in a spoon."],
	["first down.jpg",			"Cheeeeck out my HarbaughStrong band!"],
	["oops i did it again.jpg",	"Oops!..  I did it again. I played with your heart..."],
	["files are in the headphones.jpg", "The files are IN the headphones??"],
	["spirit fingers.jpg",		"Spirit Fingers!"],
	["interception.gif",		"They inceptioned us!!?"],
	["touchdown.jpg",			"I love you this much"],
	["field goal.jpg",			"Wowwwww thats a big TV screen!"],
	["i love smiling, smiling's my favorite.jpg", "I love smiling, smiling's my favorite!"]
];