var IMAGES = [
	["1.jpg",										"Ahhh a Dementor!!!"],
	["victory dance.jpg",							"Opa Harbaugh Style!"],
	["squishy.jpg",									"Bad Squishy! Bad Squishy!"],
	["angry elf.jpg",								"Harbaugh's an angry elf!"],
	["i don't know what we're yelling about.jpg", 	"I DON'T EVEN KNOW WHAT WE ARE YELLING ABOUT!"],
	["3.jpg", 										"Ohhhh Snap!"],
	["from now on, i'm calling it a football hat.jpg","From now on this is called a FOOTBALL hat!!"],
	["4.jpg",										"oh no he di'iint!!!!!"],
	["5.jpg",										"I feel like I'm taking crazy pills!!!"],
	["2.jpg",										"Use the Force, Padawan"],
	["really really ridiculously good looking.jpg",	"Is there more to life than being really, really, ridiculously good looking??"],
	["three times as good.jpg", 					"What is this??? A center for amateurs?? It needs to be at least... 3 times as good!"],
	["happy and you.jpg",							"If you're happy and you know it, clap your hands!"],
	["beats by harbaugh.jpg",						"Beats By Harbaugh"],
	["mr congeniality.jpg",							"Mr. Congeniality"],
	["spoon.jpg", 									"I knew I wanted to be a football coach the first time I caught my reflection in a spoon."],
	["first down.jpg",								"Cheeeeck out my HarbaughStrong band!"],
	["am i doing it is this a smile.jpg",			"Am I doing it right? I'm smiling? I'm smiling!"],
	["oops i did it again.jpg",						"Oops!..  I did it again. I played with your heart..."],
	["files are in the headphones.jpg", 			"The files are IN the headphones??"],
	["spirit fingers.jpg",							"Spirit Fingers!"],
	["hey i just met you.jpg",						"Hey, I just met you, and this is craaaaaazyy..."],
	["interception.gif",							"They inceptioned us!!?"],
	["touchdown.jpg",								"I love you this much"],
	["field goal.jpg",								"Wowwwww thats a big TV screen!"],
	["i love smiling, smiling's my favorite.jpg", 	"I love smiling, smiling's my favorite!"]
];